[project]
name = "techdoc-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "cloudscraper>=1.2.71",
    "httpx[http2]>=0.28.1",
    "loguru>=0.7.3",
    "lxml>=6.1.0",
    "marker-pdf>=1.10.2",
    "pdfminer>=20191125",
    "pdfminer-six>=20260107",
    "pi-heif>=0.22.0",
    "unstructured>=0.22.27",
]
