[project]
name = "techdoc-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "cloudscraper>=1.2.71",
    "httpx[http2]>=0.28.1",
    "ipykernel>=7.2.0",
    "loguru>=0.7.3",
    "lxml>=6.1.0",
    "marker-pdf>=1.10.2",
    "matplotlib>=3.10.9",
    "nltk>=3.9.4",
    "openai>=1.109.1",
    "pageindex>=0.2.8",
    "pandas>=3.0.3",
    "pdfminer>=20191125",
    "pdfminer-six>=20260107",
    "pi-heif>=0.22.0",
    "psycopg[binary]>=3.3.4",
    "python-dotenv>=1.2.2",
    "seaborn>=0.13.2",
    "spacy>=3.8.14",
    "textstat>=0.7.13",
    "unstructured>=0.22.27",
    "wordcloud>=1.9.6",
    "yake>=0.7.3",
]
